src/main/java/com/vesmax/model/Services.java
package com.vesmax.model;
// Generated Aug 4, 2019 6:35:03 PM by Hibernate Tools 5.1.7.Final


import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Services generated by hbm2java
 */
@Entity
@Table(name = "services", schema = "dbo", catalog = "Qlspa")
public class Services {

	private Integer id;
	private String name;
	private Float price;
	private String images;
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public Services() {
	}

	public Services(String name, Float price, String images) {
		this.name = name;
		this.price = price;
		this.images = images;
	}

	public Services(Integer id, String name, Float price, String images) {
		this.id = id;
		this.name = name;
		this.price = price;
		this.images = images;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Price", precision = 24, scale = 0)
	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	@Column(name = "Images")
	public String getImages() {
		return this.images;
	}

	public void setImages(String images) {
		this.images = images;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "services")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}

src/main/java/com/vesmax/controller/ServiceController.java
package com.vesmax.controller;

import javax.servlet.ServletContext;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartFile;

import com.vesmax.model.Services;
import com.vesmax.security.UploadConfig;
import com.vesmax.service.ServiceService;
import com.vesmax.service.ServiceServiceimpl;

@Controller
@RequestMapping(value = "/admin/")
public class ServiceController {
	ServiceService serviceService = new ServiceServiceimpl();
	@Autowired
	ServletContext ctx;
	@Autowired
	UploadConfig UploadConfig;

	@GetMapping("service")
	public String List(Model model) {
		model.addAttribute("service", serviceService.list());
		return "admin/service/List";
	}

	@GetMapping("service-add")
	public String addService(Model model) {
		return "admin/service/addService";
	}

	@PostMapping("service-process")
	public String addServices(ModelMap model, @RequestParam("photo2") MultipartFile image,
			@RequestParam("name") String name, @RequestParam("price") float price) {
		String photo = UploadConfig.uploadImage(model, image);
		if (serviceService.Create(new Services(name, price, photo)) == true) {
			model.addAttribute("services", serviceService.list());
			return "redirect: service";
		} else {
			model.addAttribute("error", "Thêm phòng ban thất bại");
			return "redirect: service-add";
		}
	}

	@GetMapping(value = "/service-delete/{id}")
	public String Delete(Model model, @PathVariable("id") int serviceId) {
		Services services = serviceService.findById(serviceId);
		serviceService.Delete(services);
		model.addAttribute("service", serviceService.list());

		return "redirect: /Spa_V1/admin/service	";
	}

	@GetMapping(value = "/service-update/{id}")
	public String update(Model model, @PathVariable("id") int serviceId) {
		Services services = serviceService.findById(serviceId);
		model.addAttribute("service", services);
		System.out.println("hihihihihihi");
		return "admin/service/update";
	}

	@RequestMapping(value = "service-update2", method = RequestMethod.POST)
	public String update2(ModelMap model, @RequestParam("id") int id, @RequestParam("name") String name,
			@RequestParam("photo2") MultipartFile image, @RequestParam("price") float price) {
		String photo = UploadConfig.uploadImage(model, image);
		if (serviceService.Update(new Services(id, name, price, photo)) == true) {
			System.out.println("hahahahahaah");
			model.addAttribute("services", serviceService.list());
			return "redirect: /Spa_V1/admin/service";
		} else {
			model.addAttribute("error", "Thêm phòng ban thất bại");
			return "redirect: service-add";
		}
	}

	// public String uploadImage(ModelMap map, MultipartFile image) {
	// if (image.isEmpty()) {
	// System.out.println("File error");
	// return "";
	// } else {
	// try {
	// String path = ctx.getRealPath("/resources/assets/img/") +
	// image.getOriginalFilename();
	// System.out.println("do upload"+path);
	// image.transferTo(new File(path));
	// return image.getOriginalFilename();
	// } catch (Exception e) {
	// System.out.println("Loi: " + e);
	// return "";
	// }
	// }
	// }
}

src/main/java/com/vesmax/controller/StaffsController.java
package com.vesmax.controller;

import java.io.File;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.Date;
import java.util.Enumeration;
import java.util.EventListener;
import java.util.Map;
import java.util.Set;

import javax.servlet.Filter;
import javax.servlet.FilterRegistration;
import javax.servlet.RequestDispatcher;
import javax.servlet.Servlet;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.ServletRegistration;
import javax.servlet.SessionCookieConfig;
import javax.servlet.SessionTrackingMode;
import javax.servlet.FilterRegistration.Dynamic;
import javax.servlet.descriptor.JspConfigDescriptor;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartFile;

import com.vesmax.model.Services;
import com.vesmax.model.Staffs;
import com.vesmax.service.StaffService;
import com.vesmax.service.StaffServiceimpl;

@Controller
@RequestMapping(value = "/admin/")
public class StaffsController {
	StaffService staffService = new StaffServiceimpl();
ServletContext context = new ServletContext() {
		
		@Override
		public void setSessionTrackingModes(Set<SessionTrackingMode> sessionTrackingModes) {
			// TODO Auto-generated method stub
			
		}
		
		@Override
		public boolean setInitParameter(String name, String value) {
			// TODO Auto-generated method stub
			return false;
		}
		
		@Override
		public void setAttribute(String name, Object object) {
			// TODO Auto-generated method stub
			
		}
		
		@Override
		public void removeAttribute(String name) {
			// TODO Auto-generated method stub
			
		}
		
		@Override
		public void log(String message, Throwable throwable) {
			// TODO Auto-generated method stub
			
		}
		
		@Override
		public void log(Exception exception, String msg) {
			// TODO Auto-generated method stub
			
		}
		
		@Override
		public void log(String msg) {
			// TODO Auto-generated method stub
			
		}
		
		@Override
		public SessionCookieConfig getSessionCookieConfig() {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public Enumeration<Servlet> getServlets() {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public Map<String, ? extends ServletRegistration> getServletRegistrations() {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public ServletRegistration getServletRegistration(String servletName) {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public Enumeration<String> getServletNames() {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public String getServletContextName() {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public Servlet getServlet(String name) throws ServletException {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public String getServerInfo() {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public Set<String> getResourcePaths(String path) {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public InputStream getResourceAsStream(String path) {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public URL getResource(String path) throws MalformedURLException {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public RequestDispatcher getRequestDispatcher(String path) {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public String getRealPath(String path) {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public RequestDispatcher getNamedDispatcher(String name) {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public int getMinorVersion() {
			// TODO Auto-generated method stub
			return 0;
		}
		
		@Override
		public String getMimeType(String file) {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public int getMajorVersion() {
			// TODO Auto-generated method stub
			return 0;
		}
		
		@Override
		public JspConfigDescriptor getJspConfigDescriptor() {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public Enumeration<String> getInitParameterNames() {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public String getInitParameter(String name) {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public Map<String, ? extends FilterRegistration> getFilterRegistrations() {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public FilterRegistration getFilterRegistration(String filterName) {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public Set<SessionTrackingMode> getEffectiveSessionTrackingModes() {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public int getEffectiveMinorVersion() {
			// TODO Auto-generated method stub
			return 0;
		}
		
		@Override
		public int getEffectiveMajorVersion() {
			// TODO Auto-generated method stub
			return 0;
		}
		
		@Override
		public Set<SessionTrackingMode> getDefaultSessionTrackingModes() {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public String getContextPath() {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public ServletContext getContext(String uripath) {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public ClassLoader getClassLoader() {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public Enumeration<String> getAttributeNames() {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public Object getAttribute(String name) {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public void declareRoles(String... roleNames) {
			// TODO Auto-generated method stub
			
		}
		
		@Override
		public <T extends Servlet> T createServlet(Class<T> clazz) throws ServletException {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public <T extends EventListener> T createListener(Class<T> clazz) throws ServletException {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public <T extends Filter> T createFilter(Class<T> clazz) throws ServletException {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public javax.servlet.ServletRegistration.Dynamic addServlet(String servletName,
				Class<? extends Servlet> servletClass) {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public javax.servlet.ServletRegistration.Dynamic addServlet(String servletName, Servlet servlet) {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public javax.servlet.ServletRegistration.Dynamic addServlet(String servletName, String className) {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public void addListener(Class<? extends EventListener> listenerClass) {
			// TODO Auto-generated method stub
			
		}
		
		@Override
		public <T extends EventListener> void addListener(T t) {
			// TODO Auto-generated method stub
			
		}
		
		@Override
		public void addListener(String className) {
			// TODO Auto-generated method stub
			
		}
		
		@Override
		public Dynamic addFilter(String filterName, Class<? extends Filter> filterClass) {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public Dynamic addFilter(String filterName, Filter filter) {
			// TODO Auto-generated method stub
			return null;
		}
		
		@Override
		public Dynamic addFilter(String filterName, String className) {
			// TODO Auto-generated method stub
			return null;
		}
	};

	@GetMapping("staffs")
	public String List(Model model) {
		model.addAttribute("staffs", staffService.list());
		return "admin/staffs/List";
	}

	@GetMapping("staffs-add")
	public String addService(Model model) {
		return "admin/staffs/addStaffs";
	}

	@PostMapping("add-staffs")
	public String addServices(ModelMap model,@RequestParam("photo") MultipartFile image, @RequestParam("name") String name, @RequestParam("gender") boolean gender,
			@RequestParam("birthday") Date birthday,
			@RequestParam("email") String email, @RequestParam("phone") String phone,
			@RequestParam("salary") int salary) {
		System.out.println(name);
		String photo = uploadImage(model, image);
		if (staffService.Create(new Staffs(name, gender, birthday, photo, email, phone, salary)) == true) {
			model.addAttribute("services", staffService.list());
			return "redirect: staffs";
		} else {
			model.addAttribute("error", "Thêm phòng ban thất bại");
			return "redirect: staffs-add";
		}
	}

	@GetMapping(value = "/staffs-delete/{id}")
	public String Delete(Model model, @PathVariable("id") int staffsId) {
		Staffs staffs = staffService.findById(staffsId);
		staffService.Delete(staffs);
		model.addAttribute("staffs", staffService.list());

		return "redirect: /Spa_V1/admin/staffs	";
	}

	@GetMapping(value = "/staffs-update/{id}")
	public String update(Model model, @PathVariable("id") int staffsId) {
		Staffs staffs = staffService.findById(staffsId);
		model.addAttribute("staffs", staffs);
		System.out.println("hihihihihihi");
		return "admin/staffs/update";
	}

	@RequestMapping(value = "update-staffs", method = RequestMethod.POST)

src/main/webapp/WEB-INF/pages/admin/service/List.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<jsp:include page="../include/_head.jsp"></jsp:include>

<div class="container-fluid">


	<div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog"
		aria-labelledby="myModalLabel" aria-hidden="true">
		<div style="top: 25%;" class="modal-dialog">
			<div style="border-radius: 10px" class="modal-content">

				<div
					style="padding: 10px 40px 10px 20px; background-color: #fb0404; border-top-left-radius: 10px; border-top-right-radius: 10px;"
					class="modal-header">

					<h2
						style="font-size: 28px; color: #fff; margin-left: 30%; text-align: center;"
						class="modal-title" id="myModalLabel">Delete confirm</h2>
				</div>



				<div class="modal-body">

					<p style="text-align: center; font-size: 19px;">Are you sure to
						delete this item?</p>
					<p
						style="text-align: center; font-style: italic; font-weight: bold;"
						id="name2"></p>
					<p class="debug-url"></p>
				</div>

				<div class="modal-footer">
					<button type="button" class="btn btn-basic" data-dismiss="modal">Cancel</button>
					<a style="margin-right: 40%" class="btn btn-danger btn-ok">Delete</a>
				</div>
			</div>
		</div>
	</div>


	<script>
		$('#confirm-delete').on(
				'show.bs.modal',
				function(e) {
					$(this).find('.btn-ok').attr('href',
							$(e.relatedTarget).data('href'));
					$('#name2').text($('#name').html())
				});
		setTimeout(function() {
			$('#HidemyDIV').fadeOut('slow');
		}, 1000);
	</script>


	<!-- Page Heading -->

	<div class="card-header py-3">
		<a class="btn btn-primary" href="service-add"> Thêm dịch vụ </a>
	</div>

	<!-- DataTales Example -->
	<div class="card shadow mb-4">
		<div class="card-body">
			<div class="table-responsive">
				<table id="example" class="table table-striped table-bordered"
					style="width: 100%">
					<thead>
						<tr>
							<th>Name</th>
							<th>Email</th>
							<th>Image</th>
							<th>Action</th>


						</tr>
					</thead>

					<tbody>
						<c:forEach items="${service }" var="item">

							<tr>

								<td>${item.name }</td>
								<td>${item.price }</td>
								<td><img alt="Image" width="150px" height="150px"
									src="${pageContext.request.contextPath}/resources/assets/img/${item.images}"></td>
								<td><a class="btn btn-primary"
									href="service-update/${item.id }"> <i class="fa fa-edit"></i>
								</a>
									<button
										class="tabledit-delete-button btn btn-danger waves-effect waves-light"
										data-href="service-delete/${item.id }" data-toggle="modal"
										data-target="#confirm-delete">
										<i class="fa fa-trash"></i>
									</button></td>

							</tr>
						</c:forEach>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
<jsp:include page="../include/_footer.jsp"></jsp:include>

src/main/webapp/WEB-INF/pages/admin/service/addService.jsp
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<jsp:include page="../include/_head.jsp"></jsp:include>

<div class="container-fluid">


	<div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog"
		aria-labelledby="myModalLabel" aria-hidden="true">
		<div style="top: 25%;" class="modal-dialog">
			<div style="border-radius: 10px" class="modal-content">

				<div
					style="padding: 10px 40px 10px 20px; background-color: #fb0404; border-top-left-radius: 10px; border-top-right-radius: 10px;"
					class="modal-header">

					<h2
						style="font-size: 28px; color: #fff; margin-left: 30%; text-align: center;"
						class="modal-title" id="myModalLabel">Delete confirm</h2>
				</div>



				<div class="modal-body">

					<p style="text-align: center; font-size: 19px;">Are you sure to
						delete this item?</p>
					<p
						style="text-align: center; font-style: italic; font-weight: bold;"
						id="name2"></p>
					<p class="debug-url"></p>
				</div>

				<div class="modal-footer">
					<button type="button" class="btn btn-basic" data-dismiss="modal">Cancel</button>
					<a style="margin-right: 40%" class="btn btn-danger btn-ok">Delete</a>
				</div>
			</div>
		</div>
	</div>


	<script>
		$('#confirm-delete').on(
				'show.bs.modal',
				function(e) {
					$(this).find('.btn-ok').attr('href',
							$(e.relatedTarget).data('href'));
					$('#name2').text($('#name').html())
				});
		setTimeout(function() {
			$('#HidemyDIV').fadeOut('slow');
		}, 1000);
	</script>

	<!-- DataTales Example -->
	<div class="card shadow mb-4">

  	<div style="padding: 50px" class="container">
  <h2 style="margin-left: 50px">Thêm dịch vụ</h2>
  <form class="form-horizontal" action="service-process" method="POST" enctype="multipart/form-data">
    <div class="form-group">
      <label style="margin-left: 20px" class="control-label col-sm-2" for="email">Tên dịch vụ:</label>
      <div class="col-sm-10">
        <input required type="text" class="form-control" id="" placeholder="Nhập tên dịch vụ" name="name">
      </div>
    </div>
    <div class="form-group">
      <label style="margin-left: 20px" class="control-label col-sm-2" for="pwd">Giá:</label>
      <div class="col-sm-10">          
        <input type="number" required class="form-control" id="" placeholder="Nhập giá dịch vụ" name="price">
      </div>
    </div>
    <div class="form-group">
      <label style="margin-left: 20px" class="control-label col-sm-2" for="pwd">Ảnh:</label>
      <div class="col-sm-10">          
        <input type="file"   id="photo" required accept="image/gif, image/jpeg, image/png" name="photo2">
      </div>
    </div>
    <div class="form-group">        
      <div  class="col-sm-offset-2 col-sm-10">
        <button style="float: right;" type="submit" class="btn btn-success">Xác nhận</button>
      </div>
    </div>
  </form>
</div>
	</div>
</div>
<jsp:include page="../include/_footer.jsp"></jsp:include>

src/main/webapp/WEB-INF/pages/admin/service/update.jsp
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<jsp:include page="../include/_head.jsp"></jsp:include>

<div class="container-fluid">


	<div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog"
		aria-labelledby="myModalLabel" aria-hidden="true">
		<div style="top: 25%;" class="modal-dialog">
			<div style="border-radius: 10px" class="modal-content">

				<div
					style="padding: 10px 40px 10px 20px; background-color: #fb0404; border-top-left-radius: 10px; border-top-right-radius: 10px;"
					class="modal-header">

					<h2
						style="font-size: 28px; color: #fff; margin-left: 30%; text-align: center;"
						class="modal-title" id="myModalLabel">Delete confirm</h2>
				</div>



				<div class="modal-body">

					<p style="text-align: center; font-size: 19px;">Are you sure to
						delete this item?</p>
					<p
						style="text-align: center; font-style: italic; font-weight: bold;"
						id="name2"></p>
					<p class="debug-url"></p>
				</div>

				<div class="modal-footer">
					<button type="button" class="btn btn-basic" data-dismiss="modal">Cancel</button>
					<a style="margin-right: 40%" class="btn btn-danger btn-ok">Delete</a>
				</div>
			</div>
		</div>
	</div>


	<script>
		$('#confirm-delete').on(
				'show.bs.modal',
				function(e) {
					$(this).find('.btn-ok').attr('href',
							$(e.relatedTarget).data('href'));
					$('#name2').text($('#name').html())
				});
		setTimeout(function() {
			$('#HidemyDIV').fadeOut('slow');
		}, 1000);
	</script>

	<!-- DataTales Example -->
	<div class="card shadow mb-4">

  	<div class="container">
  <h2>Sửa dịch vụ</h2>
  <form class="form-horizontal" action="${pageContext.request.contextPath }/admin/service-update2" method="POST" enctype="multipart/form-data">
  <input  type="hidden" class="form-control" id="" value="${service.id}" placeholder="Nhập tên dịch vụ" name="id">
    <div class="form-group">
      <label class="control-label col-sm-2" for="email">Tên dịch vụ:</label>
      <div class="col-sm-10">
        <input required type="text" class="form-control" value="${service.name }" id="" placeholder="Nhập tên dịch vụ" name="name">
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-2" for="pwd">Giá:</label>
      <div class="col-sm-10">          
        <input required type="number" class="form-control" value="${service.price }" id="" placeholder="Nhập giá dịch vụ" name="price">
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-2" for="pwd">Ảnh:</label>
      <div class="col-sm-10">          
        <input type="file" required  id="photo" accept="image/gif, image/jpeg, image/png" name="photo2">
      </div>
    </div>
    <div class="form-group">        
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-default">Xác nhận</button>
      </div>
    </div>
  </form>
</div>
	</div>
</div>
<jsp:include page="../include/_footer.jsp"></jsp:include>